theme: jekyll-theme-hacker
   { themeVariable: '--ion-color-primary', value: '#222020'},
   { themeVariable: '--ion-item-color', value: '#000'},
   { themeVariable: '--ion-color-text', value: '#000'},
   { themeVariable: '--ion-background-color', value: '#ffffff'},
   { themeVariable: '--ion-card-text', value: '#222020'},
   { themeVariable: '--ion-title-text', value: '#ffffff'}